---
etc_hosts_path: "/etc/hosts"
ntp_header: "^#.*NTP.*"
ds_header: '^#.*D(eep)?\s*?S(ecurity)?.*'
ocs_header: "^#.*OCS.*"
tw_header: "^#.*T(rip)?W(ire)?.*"

header_entries:
  - regexp: "{{ ntp_header }}"
    line: "\n#---NTP---\n\n"
    label: "NTP"

  - regexp: "{{ ds_header }}"
    line: "\n#---Deep Security---\n\n"
    label: "Deep Security"

  - regexp: "{{ ocs_header }}"
    line: "\n#---OCS---\n\n"
    label: "OCS"

  - regexp: "{{ tw_header }}"
    line: "\n#---TripWire---\n\n"
    label: "TripWire"

entries:
  - ip: 172.31.35.9
    d_names:
      - ntpserver
    insertafter: "{{ ntp_header }}"

  - ip: 172.31.35.35
    d_names:
      - ntpserver2
    insertafter: "{{ ntp_header }}"

  - ip: 172.31.35.37
    d_names:
      - ntpserver3
    insertafter: "{{ ntp_header }}"

  - ip: 172.31.229.12
    d_names:
      - secdsapp01
      - secdsapp01.example.com
    insertafter: "{{ ds_header }}"

  - ip: 172.31.229.13
    d_names:
      - secdsapp02
      - secdsapp02.example.com
    insertafter: "{{ ds_header }}"

  - ip: 172.31.229.14
    d_names:
      - secdsapp03
      - secdsapp03.example.com
    insertafter: "{{ ds_header }}"

  - ip: 192.168.64.108
    d_names:
      - ocs.example.com
    insertafter: "{{ ocs_header }}"

  - ip: 172.31.229.16
    d_names:
      - tripwire.example.com
    insertafter: "{{ tw_header }}"
