---
- name: Bootstrap
  hosts: client1
  become: true
  gather_facts: false
  roles:
    - bootstrap

- name: Server Setup
  hosts: client1
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: server_setup
      tags: server_setup
      # override variables down here
      # vars:
      #   etc_hosts_path: /tmp/hosts

    # - role: etc_hosts
    #   tags: etc_hosts
    # override variable here
    # vars:
    #   etc_hosts_path: /etc/hosts

    # - role: splunk
    #   tags: splunk

- name: OS Hardening
  hosts: client1
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: os_hardening
      tags: os_hardening

- name: OS Patching
  hosts: client1
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: os_patching
      tags: os_patching
