---
- name: Bootstrap
  hosts: client1
  become: true
  gather_facts: false
  tags: bootstrap-play
  roles:
    - role: bootstrap
      tags: bootstrap
      # uncomment to enable proxy
      # vars:
      #   proxy_env:
      #     http_proxy: http://localhost:1337
      #     https_proxy: https://localhost:1337

- name: Server Setup
  hosts: client1
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags: server-setup-play
  roles:
    - role: server_setup
      tags: server_setup
      # override variables down here
      # vars:
      #   etc_hosts_path: /tmp/hosts

- name: OS Hardening
  hosts: client1
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags: os-hardening-play
  roles:
    - role: os_hardening
      tags: os_hardening

- name: OS Patching
  hosts: client1
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags: os-patching-play
  roles:
    - role: os_patching
      tags: os_patching
