---
- name: OCS Agent
  block:
    - name: OCS Agent -- Check crontab
      ansible.builtin.cron:
        name: "ocs_agent"
        minute: "0"
        hour: "2"
        weekday: "6"
        job: "/usr/opt/ocs-rhel8/bin/ocsinventory-agent -s=https://MBBASTPRDAPP001.maybank.com.my/ocsinventory --ssl=0 -f"

  rescue:
    - name: OCS Agent -- flush handlers
      ansible.builtin.meta: flush_handlers

    - name: OCS Agent -- Caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
