---
- name: audit.rules
  block:
    - name: audit.rules -- include vars
      ansible.builtin.include_vars:
        file: vars_audit_rules.yml

    - name: audit.rules -- Delete audit.rules file
      ansible.builtin.file:
        path: "{{ audit_rules_path }}"
        state: absent
      failed_when: false

    - name: audit.rules -- generate rules for SUID and SGID files
      ansible.builtin.shell: >
        find / -xdev \( -perm -4000 -o -perm -2000 \) -type f
        | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=1000
        -F auid!=4294967295 -k privileged" }'
      register: rules_out

    - name: audit.rules -- Create audit.rules file
      vars:
        rules:
          "x86_64": "{{ rules_b64 }}"
          "x86": "{{ rules_b32 }}"
      ansible.builtin.blockinfile:
        create: true
        path: "{{ audit_rules_path }}"
        block: |
          {{ rules[arch] }}
          {{ rules_out.stdout }}

    - name: audit.rules -- restart service
      ansible.builtin.service:
        name: auditd
        state: restarted

  rescue:
    - name: audit.rules -- flush handlers
      ansible.builtin.meta: flush_handlers

    - name: audit.rules -- caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
