---
- name: Inactive password lock
  block:
    - name: Inactive password lock -- check inactive period
      ansible.builtin.shell: "useradd -D | grep --color=none -oP '(?<=INACTIVE=).*'"
      register: period_out
      changed_when: false
      failed_when: false

    - name: Inactive password lock -- set inactive period to {{ period }}
      vars:
        period: 30
      ansible.builtin.command: "useradd -D -f {{ period }}"
      changed_when: true
      register: out
      when: period_out.stdout | int != period

  rescue:
    - name: Inactive password lock -- flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Inactive password lock -- caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
