---
- name: /var/log/
  block:
    - name: /var/log/ -- include vars
      ansible.builtin.include_vars:
        file: vars_var_log.yml

    - name: /var/log/ -- check if files exist
      ansible.builtin.stat:
        path: "{{ item.name }}"
      register: check_files_out
      loop: "{{ files }}"
      loop_control:
        label: "{{ item.name }}"

    - name: /var/log/ -- set files permission if exist
      loop: "{{ check_files_out.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      when: item.stat.exists
      ansible.builtin.file:
        path: "{{ item.item.name }}"
        owner: "{{ item.item.owner }}"
        group: "{{ item.item.group }}"
        mode: "{{ item.item.mode }}"
        state: file
      ignore_errors: true

    - name: /var/log/ -- check if directories exist
      ansible.builtin.stat:
        path: "{{ item.name }}"
      register: check_dirs_out
      loop: "{{ directories }}"
      loop_control:
        label: "{{ item.name }}"

    - name: /var/log/ -- set directories permission if exist
      loop: "{{ check_dirs_out.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      when: item.stat.exists
      ansible.builtin.file:
        path: "{{ item.item.name }}"
        owner: "{{ item.item.owner }}"
        group: "{{ item.item.group }}"
        mode: "{{ item.item.mode }}"
        state: directory
        recurse: true
      ignore_errors: true

  rescue:
    - name: /var/log/ -- flush handlers
      ansible.builtin.meta: flush_handlers

    - name: /var/log/ -- caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
