---
tripwire_tgz: "tripwire.tgz"
tripwire_base_dir: "/etc"

tripwire_files:
  - "{{ tripwire_base_dir }}/tripwire/metadata.yml"
  - "{{ tripwire_base_dir }}/tripwire/twagent.conf"
  - "{{ tripwire_base_dir }}/tripwire/registration_pre_shared_key.txt"

tripwire_pkgs:
  - name: axon-agent
    pkg: axon-agent-installer-linux-x64.rpm
  - name: tw-eg-driver-rhel
    pkg: tw-eg-driver-rhel-1.5.2.195-1.x86_64.rpm
  - name: tw-eg-service
    pkg: tw-eg-service-1.5.1.239-1.x86_64.rpm

tripwire_services:
  - tripwire-axon-agent
  - tw-eg-service
