---
- name: /var/log/
  block:
    - name: Check if files exist
      ansible.builtin.stat:
        path: "{{ item.name }}"
      register: check_files_out
      loop: "{{ files }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set files permission if exist
      vars:
        file: "{{ item.item }}"
      loop: "{{ check_files_out.results }}"
      loop_control:
        label: "{{ file.name }}"
      when: item.stat.exists
      ansible.builtin.file:
        path: "{{ file.name }}"
        owner: "{{ file.owner }}"
        group: "{{ file.group }}"
        mode: "{{ file.mode }}"
        state: file
      ignore_errors: true

    - name: Check if directories exist
      ansible.builtin.stat:
        path: "{{ item.name }}"
      register: check_dirs_out
      loop: "{{ directories }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set directories permission if exist
      vars:
        dir: "{{ item.item }}"
      loop: "{{ check_dirs_out.results }}"
      loop_control:
        label: "{{ dir.name }}"
      when: item.stat.exists
      ansible.builtin.file:
        path: "{{ dir.name }}"
        owner: "{{ dir.owner }}"
        group: "{{ dir.group }}"
        mode: "{{ dir.mode }}"
        state: directory
        recurse: true
      ignore_errors: true

  rescue:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
