---
- name: auditd.conf
  ansible.builtin.import_tasks:
    file: auditd_conf.yml
  tags: auditd_conf

- name: audit_rules
  ansible.builtin.import_tasks:
    file: audit_rules.yml
  tags: audit_rules
