---
- name: Inactive password lock
  block:
    - name: Check inactive period
      ansible.builtin.shell: >
        useradd -D | grep --color=none -oP '(?<=INACTIVE=).*'
      register: period_out
      changed_when: period_out.stdout | int != period
      failed_when: false

    - name: "Set inactive period to {{ period }}"
      ansible.builtin.command: "useradd -D -f {{ period }}"
      changed_when: true
      register: out
      when: period_out is changed

  rescue:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
