---
- name: OCS Agent
  block:
    - name: Check crontab
      ansible.builtin.cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute | default(omit) }}"
        hour: "{{ item.hour | default(omit) }}"
        day: "{{ item.day | default(omit) }}"
        month: "{{ item.month | default(omit) }}"
        weekday: "{{ item.weekday | default(omit) }}"
        user: "{{ item.root | default(omit) }}"
        job: "{{ item.job }}"
      loop: "{{ ocs_crontab }}"
      loop_control:
        label: "{{ item.name }}"

  rescue:
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Caught error
      ansible.builtin.debug:
        msg: Troubleshoot me
