---
sshd_conf_path: /etc/ssh/sshd_config
sshd_conf:
  RedHat_8:
    - key: "Protocol"
      value: "2"

    - key: "RhostsRSAAuthentication"
      value: "no"

    - key: "Ciphers"
      value: "aes128-ctr,aes192-ctr,aes256-ctr"

    - key: "MACs"
      value: "hmac-sha1,umac-64@openssh.com"

    - key: "KexAlgorithms"
      value: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1"

  RedHat_7:
    - key: "Protocol"
      value: "2"

    - key: "RhostsRSAAuthentication"
      value: "no"

    - key: "Ciphers"
      value: "aes128-ctr,aes192-ctr,aes256-ctr"

    - key: "MACs"
      value: "hmac-sha1,umac-64@openssh.com,hmac-ripemd160"

    - key: "KexAlgorithms"
      value: "diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1"
