---
os_family: "{{ ansible_facts['distribution'] }}"
major_version: "{{ ansible_facts['distribution_major_version'] }}"
dist: "{{ os_family + '_' + major_version }}"
arch: "{{ ansible_facts['architecture'] }}"

nagios_tarball: "nagios.tgz"
nagios_dest: /usr/local/
